### ISSUE TITLE
Making signature matrices w/o using external annotations?

### ISSUE THREAD

**Issue by cnk113** [wilsonlabgroup/scMappR#4]
Hello,

I'm trying to generate sig matrices w/ process_dgTMatrix_lists, however of many cell types I have. The number of matrices/cell types get decreased in the output. Also the cell types I have don't have a external references so ideally it would be nice to generate the matrices w/o any bias. Is there an option to keep the input number of matrices and just keep the signature matrix as is?

Best,
Chang

**Comment by DustinSokolowski** [comment]
Hey Chang!

I'm very sorry for the slow reply, I've been out of town.

I think I'm having a bit of trouble trying to tell what you mean by cell-types and matrices. I am going to treat this question the same as if your gene symbols do not fit mouse and human and such, you want the signature matrix to essentially be cluster 0-N as identified by Seurat V4.

What I would do is follow the "Signature matrix from Seurat object with named cell-type" section of the Vignette, excluding the "levels line of code". Please see below.

https://cran.r-project.org/web/packages/scMappR/vignettes/scMappR_Vignette.html#processing-scrna-seq-count-data-into-a-signature-matrix.

`data(sm) # load scRNAseq count data` 

This line below is the basic wrapper for Seurat processing. The only thing that "theSpecies" does here is that if you use "human", then it assumes mitochondrial genes are "MT-", if it = "mouse", then we assume mitochondrial genes start with "mt-". If you don't know your mitochondrial genes just use "human" and the data will be processed but without % mt counted and corrected for (generally not recommended but sometimes it cant be helped). If you do know you mt genes, just stick a "MT-" on the symbols and call your species "human".
`seurat_example <- process_from_count(toProcess, "test_vignette",theSpecies  = "mouse")` 

 `generes <- seurat_to_generes(pbmc = seurat_example, test = "wilcox") # identify cell-type markers` 

 `gene_out <- generes_to_heatmap(generes, make_names = FALSE) # make the signature matrix without re-identifying cell-type names.`

This Should for all intents and purposes work. If you already had your clusters labelled but you want the seurat count processing, then just label each of your cells with the RenameIdents function in Seurat (or some manual labelling) and continue on as normal.

I hope this helps and please let me know if you have any other questions. If not then please close in your reply. 

Thanks!
Dustin

**Comment by cnk113** [comment]
Woops sorry about the typo in the first sentence, what pretty much happens if I run process_dgTMatrix_lists on my list of mtx, the output lost of sig matrices are smaller. I think you're workflow should work since it's not re-identifying (and maybe pruning the cell type matrices?). 

Thanks,
Chang

**Comment by DustinSokolowski** [comment]
Thanks so much! That is quite interesting. Is there any chance that the data you're using is public? I'd be interested in seeing if I can reproduce the problem within the main `process_dgTMatrix_lists`. No problem if not!

Best,
Dustin

**Comment by helianthuszhu** [comment]
Hi Dustin and Chang,
     Thanks for providing such wonderful package!
     I also have similar problem when trying my own scRNA-seq seurat object. Following your pipeline with my own already cell type-named Seurat object, it complains the bulk data does not include all the cell types I have included.
     Do you now have any resolutions on this problem?
     Thank you very much~~

Best,
Xiaoqiang

**Comment by DustinSokolowski** [comment]
Hey!

I'm guessing that either the scRNA-seq/bulk RNA-seq got inputted into the wrong variable. I'm just guessing this because it shouldn't complain about the bulk data having or not having cell-types.

Best!
Dustin

**Comment by helianthuszhu** [comment]
Dear Dustin,
Thanks for your quick reply, I followed the pipeline and came to 'scMappR_and_pathway_analysis' step, it said as following, please check.
############
Keeping genes in signature matrix that overlap with count matrix.

cell-types with markers that overlap with inputted count matrix

C1-Mature-NaiveC2-Mature-NaiveC3-Mature-NaiveC4-Mature-NaiveC5-Mature-NaiveC6-Memory-GC-dependentC7-Memory-GC-dependentC8-Memory-GC-dependentC9-Memory-GC-dependentC10-Memory-GC-dependentC11-Memory-GC-independentC12-Plasma cellsCD4-ANXA1CD4-CCR7CD4-CXCR6CD4-FOXP3CD4-GPR183CD4-PDCD1CD8-CCR7CD8-GZMKCD8-JUNCD8-TRGC2DCEndoEpiFibroGranuMT-dominantMac-APOC1Mac-C1QCMac-LILRB5Mac-RP_dominantMastMono-CD1CMono-FCN1Mono-FKBP5Mono-HSPA1BNK-CD247NK-CLIC3NK-FCGR3ANK-XCL1PlasmaProlif-STMN1

For deconvolution, we're using the top 4000 most vairable signatures

your bulk data contains the following cell types

C7-Memory-GC-dependent  C10-Memory-GC-dependent  C11-Memory-GC-independent  C12-Plasma cells  CD4-ANXA1  CD4-CCR7  CD4-FOXP3  CD4-PDCD1  CD8-CCR7  DC  Endo  Epi  Fibro  Granu  Mac-RP_dominant  Mast  Mono-FKBP5  Plasma  Prolif-STMN1  

4232
############,
as you can say, most cell types are not found there, but i checked the degs list and top markers of some of the missed cell types, they actually have some overlaps. So, probably, I am not sure what the  really issue is ?

Best,
Xiaoqiang

**Comment by helianthuszhu** [comment]
This is the code i used as below:
case_grep <- "_Yes" 
control_grep <- "_No" 
max_proportion_change <- 10 
theSpecies <- "human" 
toOut <- scMappR_and_pathway_analysis(bulk_normalized, odds_ratio_in, 
                                      bulk_DE_cors, case_grep = case_grep,
                                      control_grep = control_grep,  #rda_path = "", 
                                      max_proportion_change = 10, print_plots = TRUE, 
                                      plot_names = "scMappR_batched", theSpecies = "human", 
                                      output_directory = "scMappR_batched",
                                      sig_matrix_size = 4000, up_and_downregulated = TRUE, 
                                      internet = TRUE, toSave = TRUE, path = './')

**Comment by DustinSokolowski** [comment]
Oh!

Short answer: In The code is working and the cell-types are being filtered for decent reasons.

Long answer:

Yeah I totally get what is happening here. So scMappR estimates cell-type proportions for every cell-type as an input into the cell-weighted fold-change statistic. We filter out cells that are estimated to be present in less than 1% of the bulk RNA-seq data for technical reasons. For example: there is a proportion in the denominator and the variance difference in proportion of 0.001% vs 0.01% of the bulk sample may be an acceptable variation in RNA-seq deconvolution because the cell-type is super rare, but this could lead to a 10x inflation in cwFold-changes. 

We also filter them for biological/intuitive reasons: scMappR is used to sort DEGs detected in bulk RNA-seq into their cell-type of origin. Genes detected DE in the bulk RNA-seq are unlikely to be detected as DE as their expression may be masked by other cell-types that express the gene but not in a DE way, or getting reads from the super rare cell-type is so uncommon that there can be both false positives and negatives. This is because bulk RNA-seq homogenizes reads from all cell-types, so which cell-type a read was sequenced from is random sampling, or the weighted expectation of cell-type specificity and cell-type proportion. This phenomena is shown in the supplemental for the manuscript as well (though with less extreme proportions) in the simulations in figure 2.

**Hacking/workarounds**
You could hack this by pre-selecting cell-types that you're interested in.

Another and maybe better way is by merging clusters of the same cell-type (e.g. making all the mature-naive clusters one cell-type). merging can be effective as there are often enough shared markers that scMappR will probably just assign the a gene to multiple clusters of the same cell-type anyhow. Of course only do this if the clusters are also in the same manifold.

If you wanted to I could create an option to remove this filter but i'd be _very_ worried about false positives: there filter is there for a reason.

Hope this helps and let me know if you have other questions!

**Comment by helianthuszhu** [comment]
Dear Dustin,
          Thanks for your helpful advice and I get to understand on the filtering. However, actually I am just interested in one of the cell types associated with drug treatment, but it indeed accounts for a small percentage of all the cells or main lineage (i.e. Macropahges) in scRNA-seq data.
          Do you think it will work if I just include this interested cell type in signature matrix?
          Of course, it would be worthy to try for me if you can create an option for not filtering.
          Many thanks.

Best,
Xiaoqiang

**Comment by DustinSokolowski** [comment]
Hey! 

The way RNA-seq deconvolution works is that is assumes that each sample is made up of the cell-types within the signature matrix. Preselecting a diverse/representative group of cell-types that include the macrophage population of interest should yield the best results. You can also use the `compare_deconvolution_methods` to see which deconvolution method reflects your data best and/or which detected the macrophage population.

Because RNA-seq deconvolution works best with more samples than cell-types and you have a lot of cell-types, I'm guessing that they're erroneously detecting 0% proportions of a number of cell-types (possibly including macrophages) which would mean that you'd have to adjust the signature matrix regardless of if I make that filter toggleable.

so I'd suggest curating a subset of cell-types that are representative (including macrophages), run it again, and see if the cell-types you're interested in remain. `compare_deconvolution_methods`  will help too.

Let me know if this works for you! If not I can look at optionally removing the 1% proportion filter but I really don't think i'd trust results of that rare of a cell-type.

Best,
Dustin

**Comment by DustinSokolowski** [comment]
Also, I looked at the filter again and it's to remove cell-types rarer than 0.1% of the bulk sample rather than 1%. I really wouldn't remove this.

**Comment by helianthuszhu** [comment]
Thank you very much. I will make it try as you suggest~~

**Comment by DustinSokolowski** [comment]
good luck!
